# FastZapret конфигурация

# 0 = по числу CPU
workers = 0

# Глубина очереди драйвера и время в очереди (мс)
queue_len = 16384
queue_time_ms = 2000

# fast | balanced | aggressive
tune = balanced

# Какие сервисы обрабатывать
discord = true
youtube = true
telegram = true
roblox = true
